#!/usr/bin/perl

use strict;
use warnings;
use RRD::Simple ();

my $id = `/usr/bin/id -u`;
chomp $id;
if($id != 0) {
	die "This program needs to run as root\n";
} 
# Load modules
system("modprobe w1-gpio");
system("modprobe w1-therm");

# /sys/bus/w1/devices/28-00000534cd84/w1_slave
# 99 01 4b 46 7f ff 07 10 79 : crc=79 YES
# 99 01 4b 46 7f ff 07 10 79 t=25562

my $device_dir = "/sys/bus/w1/devices";
while(1) {
	opendir(DEVDIR, $device_dir);
	my @devices = grep(/^28-/, readdir(DEVDIR));
	foreach my $device (@devices) {
		if(-f "$device_dir/$device/w1_slave") {
			my $now = time();
			my $temp = `cat $device_dir/$device/w1_slave|grep " t=" |awk '{print \$10}'`;
			chomp $temp;
			$temp =~ s/t=//;
			$temp = sprintf("%.2f", $temp/1000);
			print "$device Temp = $temp C\n";
			my $rrd = RRD::Simple->new( file => "$device.rrd" );
			if(!-f "$device.rrd") {
				$rrd->create(temperature => "GAUGE");
			}
			$rrd->update("$device.rrd", $now, temperature => $temp);
			my %rtn = $rrd->graph(
				destination => "./",
				title => "Temperature - degrees Celsius",
				vertical_label => "C",
				interlaced => "" );
			printf("Created %s\n",join(", ",map { $rtn{$_}->[0] } keys %rtn));
			
		}
	}
	closedir DEVDIR;
	sleep 2;
}
